"""Auto-generated by ai_pulse_server.py — do not edit by hand."""
from prefab_ui.app import PrefabApp
from prefab_ui.components import (
    Badge, Card, CardContent, CardHeader, CardTitle,
    Column, H1, H3, Muted, Row, Tab, Tabs, Text,
)
from prefab_ui.components.charts import (
    BarChart, ChartSeries, PieChart,
)

with PrefabApp(css_class="max-w-6xl mx-auto p-6") as app:
    with Card():
        with CardHeader():
            CardTitle("AI Pulse — daily radar")
        with CardContent():
            with Column(gap=4):
                with Row(gap=6):
                    with Column(gap=1):
                        Muted('Bookmarks')
                        H1('15')
                    with Column(gap=1):
                        Muted('Unread')
                        H1('15')
                    with Column(gap=1):
                        Muted('Papers')
                        H1('8')
                    with Column(gap=1):
                        Muted('News')
                        H1('7')
                    with Column(gap=1):
                        Muted('CVEs')
                        H1('0')
                PieChart(data=[{'name': 'paper', 'value': 8}, {'name': 'news', 'value': 7}], data_key='value', name_key='name', show_legend=True)
                BarChart(data=[{'tag': 'ai-research', 'count': 8}, {'tag': 'cybersec', 'count': 7}],
                         series=[ChartSeries(data_key='count', label='count')],
                         x_axis='tag', show_legend=False)
                with Tabs(value="papers"):
                    with Tab('Papers', value='papers'):
                        with Column(gap=3):
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Hierarchical RL for Long-Horizon Reasoning and Decision Making')
                                        Text('This survey reviews state-of-the-art Hierarchical Reinforcement Learning (HRL) methods for long-horizon reasoning and decision-making problems.')
                                        with Row(gap=2):
                                            Badge('ai-research', variant='default')
                                        Muted('saved 2026-05-02T04:24:54+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Exploration Hacking: Can LLMs Learn to Resist RL Training?')
                                        Text("This paper investigates 'exploration hacking' where LLMs might strategically alter their exploration during RL training to influence outcomes.")
                                        with Row(gap=2):
                                            Badge('ai-research', variant='default')
                                        Muted('saved 2026-05-02T04:24:49+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Computing Equilibrium beyond Unilateral Deviation')
                                        Text('This paper studies an alternative solution concept to traditional equilibrium concepts in games, focusing on stability against multilateral deviations.')
                                        with Row(gap=2):
                                            Badge('ai-research', variant='default')
                                        Muted('saved 2026-05-02T04:24:44+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Mitigating the Vulnerability of LLMs to Adversarial Word Perturbations via a Robust Distillation Framework')
                                        Text('Large Language Models (LLMs) are highly vulnerable to adversarial word perturbations, which can subtly alter inputs to elicit unintended or harmful outputs. This paper proposes a robust distillation framework to mitigate this vulnerability.')
                                        with Row(gap=2):
                                            Badge('ai-research', variant='default')
                                        Muted('saved 2026-05-02T04:22:38+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Towards Optimal Control for Large Language Models using Reinforcement Learning: Fundamentals and Challenges')
                                        Text('The rapid advancement of Large Language Models (LLMs) has led to their widespread application across various domains. Reinforcement Learning (RL) has emerged as a promising approach to enhance the performance and alignment of LLMs, enabling them to tackle complex tasks and exhibit more human-like reasoning.')
                                        with Row(gap=2):
                                            Badge('ai-research', variant='default')
                                        Muted('saved 2026-05-02T04:22:35+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Large Language Models as a Source of Implied Knowledge')
                                        Text('This work investigates whether large language models (LLMs) can serve as an effective source of implied knowledge, specifically focusing on generating counterfactual explanations. Counterfactual explanations are statements that describe how an input would need to change to alter the output of a model.')
                                        with Row(gap=2):
                                            Badge('ai-research', variant='default')
                                        Muted('saved 2026-05-02T04:22:31+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('A Review of Large Language Models: Their Evolution, Performance, and Capabilities')
                                        Text('Large Language Models (LLMs) have recently demonstrated remarkable capabilities in natural language processing (NLP) tasks, leading to a paradigm shift in the field of artificial intelligence. This review article aims to provide a comprehensive overview of LLMs.')
                                        with Row(gap=2):
                                            Badge('ai-research', variant='default')
                                        Muted('saved 2026-05-02T04:14:32+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Diffusion Models as Multi-Agent Reinforcement Learning')
                                        Text('Diffusion models (DMs) have emerged as powerful generative models capable of generating high-quality images. We propose a novel framework that interprets diffusion models as multi-agent reinforcement learning (MARL) systems.')
                                        with Row(gap=2):
                                            Badge('ai-research', variant='default')
                                        Muted('saved 2026-05-02T04:14:27+00:00')
                    with Tab('News', value='news'):
                        with Column(gap=3):
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3("Android Banking Trojan 'MMRat' Steals User Credentials and Bypasses MFA")
                                        Text('A new Android banking Trojan named MMRat has been discovered, capable of stealing user credentials, bypassing multi-factor authentication (MFA), and taking control of devices.')
                                        with Row(gap=2):
                                            Badge('cybersec', variant='default')
                                        Muted('saved 2026-05-02T04:23:05+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Critical Zero-Day Vulnerability Found in Ivanti Connect Secure VPN Devices')
                                        Text('A critical zero-day vulnerability has been discovered in Ivanti Connect Secure VPN appliances, which has been actively exploited in the wild. This flaw could allow attackers to execute arbitrary commands on the affected devices.')
                                        with Row(gap=2):
                                            Badge('cybersec', variant='default')
                                        Muted('saved 2026-05-02T04:23:01+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Cybercrime Groups Using Vishing and SSO Abuse in Rapid SaaS Extortion Attacks')
                                        Text('Cybersecurity researchers are warning of two cybercrime groups that are carrying out "rapid, high-impact attacks" operating almost within the confines of SaaS environments, while leaving minimal traces of their actions.')
                                        with Row(gap=2):
                                            Badge('cybersec', variant='default')
                                        Muted('saved 2026-05-02T04:22:58+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('30,000 Facebook Accounts Hacked via Google AppSheet Phishing Campaign')
                                        Text('A newly discovered Vietnamese-linked operation has been observed using a Google AppSheet as a "phishing relay" to distribute phishing emails with an aim to compromise Facebook accounts.')
                                        with Row(gap=2):
                                            Badge('cybersec', variant='default')
                                        Muted('saved 2026-05-02T04:22:52+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('Critical RCE Bug Patched in Apache Flink')
                                        Text('A critical remote code execution (RCE) vulnerability (CVE-2023-34469) has been patched in Apache Flink, a popular open-source stream processing framework.')
                                        with Row(gap=2):
                                            Badge('cybersec', variant='default')
                                        Muted('saved 2026-05-02T04:15:00+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('CISA Warns of Threat Actors Actively Exploiting Ivanti EPMM Vulnerability (CVE-2023-35078)')
                                        Text('CISA has issued a warning about threat actors actively exploiting a critical vulnerability (CVE-2023-35078) in Ivanti Endpoint Manager Mobile (EPMM).')
                                        with Row(gap=2):
                                            Badge('cybersec', variant='default')
                                        Muted('saved 2026-05-02T04:14:55+00:00')
                            with Card():
                                with CardContent():
                                    with Column(gap=1):
                                        H3('New Rust-Written BlackCat Ransomware Variant Exploits Critical Veeam Bug')
                                        Text('A new variant of the BlackCat (aka ALPHV) ransomware, written in Rust, has been observed in attacks exploiting a critical vulnerability in Veeam Backup & Replication software (CVE-2023-27532).')
                                        with Row(gap=2):
                                            Badge('cybersec', variant='default')
                                        Muted('saved 2026-05-02T04:14:51+00:00')
                    with Tab('CVEs', value='cves'):
                        with Column(gap=3):
                            Muted('No cves bookmarked yet.')
